"""initial

Revision ID: 6759975632b3
Revises:
Create Date: 2026-07-24 19:28:58.476514

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6759975632b3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Identificador único da categoria"
        ),
        sa.Column(
            "name", sa.String(length=120), nullable=False, comment="Nome da categoria"
        ),
        sa.Column(
            "description", sa.Text(), nullable=True, comment="Descrição da categoria"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Data de criação do registro",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Data da última atualização",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), nullable=False, comment="ID único da permissão"),
        sa.Column(
            "nome",
            sa.String(length=100),
            nullable=False,
            comment="Nome da permissão no formato resource.action (ex: users.create)",
        ),
        sa.Column(
            "descricao",
            sa.Text(),
            nullable=True,
            comment="Descrição detalhada da permissão",
        ),
        sa.Column(
            "data_criacao",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Data e hora de criação da permissão",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Data de criação do registro",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Data da última atualização",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Tabela de permissões do sistema RBAC",
    )
    op.create_index(op.f("ix_permissions_nome"), "permissions", ["nome"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False, comment="ID único da role"),
        sa.Column(
            "nome",
            sa.String(length=100),
            nullable=False,
            comment="Nome da role (ex: admin, editor, viewer)",
        ),
        sa.Column(
            "data_criacao",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Data e hora de criação da role",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Data de criação do registro",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Data da última atualização",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Tabela de roles do sistema RBAC",
    )
    op.create_index(op.f("ix_roles_nome"), "roles", ["nome"], unique=True)
    op.create_table(
        "products",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Identificador único do produto"
        ),
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Nome do produto"
        ),
        sa.Column(
            "description", sa.Text(), nullable=True, comment="Descrição do produto"
        ),
        sa.Column(
            "price",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Preço do produto",
        ),
        sa.Column(
            "sku", sa.String(length=50), nullable=False, comment="Código SKU do produto"
        ),
        sa.Column(
            "category_id",
            sa.UUID(),
            nullable=False,
            comment="ID da categoria do produto",
        ),
        sa.Column(
            "stock_quantity",
            sa.Integer(),
            nullable=False,
            comment="Quantidade em estoque",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Se o produto está ativo"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Data de criação do registro",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Data da última atualização",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_products_category_id"), "products", ["category_id"], unique=False
    )
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=True)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False, comment="ID da role"),
        sa.Column(
            "permission_id", sa.UUID(), nullable=False, comment="ID da permissão"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Data de associação",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_roles_nome"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_nome"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
