"""init rbac

Revision ID: d052146fca64
Revises: 
Create Date: 2026-03-09 10:39:32.972278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd052146fca64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False, comment='ID único da permissão'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nome da permissão no formato resource.action (ex: users.create)'),
    sa.Column('descricao', sa.Text(), nullable=True, comment='Descrição detalhada da permissão'),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=False, comment='Data e hora de criação da permissão'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Data da última atualização'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tabela de permissões do sistema RBAC'
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False, comment='ID único da role'),
    sa.Column('nome', sa.String(length=100), nullable=False, comment='Nome da role (ex: admin, editor, viewer)'),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=False, comment='Data e hora de criação da role'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Data da última atualização'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tabela de roles do sistema RBAC'
    )
    op.create_index(op.f('ix_roles_nome'), 'roles', ['nome'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False, comment='ID da role'),
    sa.Column('permission_id', sa.UUID(), nullable=False, comment='ID da permissão'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data de associação'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_roles_nome'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
